name: Build

on:
  workflow_call:
    inputs:
      java-version:
        default: '8'
        required: false
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: zulu
          cache: gradle

      - name: Build
        run: ./gradlew build -S